import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import MetaData from "../components/layout/MetaData";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MetaData />
      <body className={inter.className}>
        <Box
          display={"flex"}
          flexDirection={"column"}
          justifyContent={"space-between"}
          height={"100%"}
        >
          <Header />
          <Box mb={4}></Box>
          {children}
          <Footer />
        </Box>
      </body>
    </html>
  );
}
